
language: python

python:
  - "3.6"
# command to install requirements
before_install:
  - "pip install -U pip"
  - "python setup.py install"
install: "pip install -r requirements.txt"
# command to run tests
script:
  - nosetests
