
language: python

python:
  - "3.6"
# command to install requirements
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install: "pip install -r requirements.txt"
# command to run tests
script:
  - nosetests
